### ISSUE TITLE
No idea how to do a search

### ISSUE THREAD

**Issue by ElectricRCAircraftGuy** [ajermakovics/eclipse-instasearch#91]
After installing it 10 minutes ago and searching all around (including googling and searching YouTube) I still don't know how to do a search with this plugin. You should probably add those instructions to the readme. Removing plugin now. I'll use "Glance Search" instead. It explains how to do a search (Ctrl + Alt + F).

**Comment by ElectricRCAircraftGuy** [comment]
Update: turns out the install failed. In my attempt to uninstall it I discovered it hadn't actually installed. After re-installing I see the "InstaSearch" box pop up at the bottom. Maybe add a note about this in the readme.

**Comment by ajermakovics** [comment]
Nice to hear it worked out. Shall we close the issue? 
Happy to accept PRs for readme improvements

**Comment by ElectricRCAircraftGuy** [comment]
Here's my pull request. Once edited (if desired) and accepted I'll close this issue.
https://github.com/ajermakovics/eclipse-instasearch/pull/92
